In [8]:
from bs4 import BeautifulSoup
import requests

webpage = requests.get("https://www.python.org/")

print(webpage)

soup = BeautifulSoup(webpage.content, "html.parser")

print(soup.prettify())

<Response [200]>
<!DOCTYPE html>
<html class="no-js" dir="ltr" lang="en">
 <head>
  <script data-domain="python.org" defer="" file-types="bz2,chm,dmg,exe,gz,json,msi,msix,pdf,pkg,tgz,xz,zip" src="https://analytics.python.org/js/script.file-downloads.outbound-links.js">
  </script>
  <meta charset="utf-8"/>
  <link href="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js" rel="prefetch"/>
  <link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" rel="prefetch"/>
  <meta content="Python.org" name="application-name"/>
  <meta content="Python.org" name="apple-mobile-web-app-title"/>
  <meta content="yes" name="apple-mobile-web-app-capable"/>
  <meta content="black" name="apple-mobile-web-app-status-bar-style"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <meta content="True" name="HandheldFriendly"/>
  <meta content="telephone=no" name="format-detection"/>
  <script async="" crossorigin="anonymous" integrity="sha256-U3hKDidudIaxBDEzwGJApJgPEf2mWk6cfMWghrAa6i0= sha384-UcmsCqcNRSLW/dV3Lo1oCi2/VaurXbib6p4HyUEOeIa/4OpsrnucrugAefzVZJfI sha512-q4t1L4xEjGV2R4hzqCa41P8jrgFUS8xTb8rdNv4FGvw7FpydVj/kkxBJHOiaoxHa8olCcx1Slk9K+3sNbsM4ug==" src="https://media.ethicalads.io/media/client/v1.4.0/ethicalads.min.js">
  </script>
  <script src="/static/js/libs/modernizr.js">
  </script>
  <link href="/static/stylesheets/style.6cb9f297dd80.css" media="all" rel="stylesheet" title="default" type="text/css">
   <link href="/static/stylesheets/mq.a4feecea96fa.css" media="not print, braille, embossed, speech, tty" rel="stylesheet" type="text/css">
    <link href="/static/stylesheets/font-awesome.bf0c425cdb73.css" media="screen" rel="stylesheet" type="text/css"/>
    <link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css" rel="stylesheet"/>
    <link href="/static/favicon.ico" rel="icon" type="image/x-icon"/>
    <link href="/static/apple-touch-icon-144x144-precomposed.png" rel="apple-touch-icon-precomposed" sizes="144x144"/>
    <link href="/static/apple-touch-icon-114x114-precomposed.png" rel="apple-touch-icon-precomposed" sizes="114x114"/>
    <link href="/static/apple-touch-icon-72x72-precomposed.png" rel="apple-touch-icon-precomposed" sizes="72x72"/>
    <link href="/static/apple-touch-icon-precomposed.png" rel="apple-touch-icon-precomposed"/>
    <link href="/static/apple-touch-icon-precomposed.png" rel="apple-touch-icon"/>
    <meta content="/static/metro-icon-144x144.png" name="msapplication-TileImage"/>
    <!-- white shape -->
    <meta content="#3673a5" name="msapplication-TileColor"/>
    <!-- python blue -->
    <meta content="#3673a5" name="msapplication-navbutton-color"/>
    <title>
     Welcome to Python.org
    </title>
    <meta content="The official home of the Python Programming Language" name="description"/>
    <meta content="Python programming language object oriented web free open source software license documentation download community" name="keywords"/>
    <meta content="website" property="og:type"/>
    <meta content="Python.org" property="og:site_name"/>
    <meta content="Welcome to Python.org" property="og:title"/>
    <meta content="The official home of the Python Programming Language" property="og:description"/>
    <meta content="https://www.python.org/static/opengraph-icon-200x200.png" property="og:image"/>
    <meta content="https://www.python.org/static/opengraph-icon-200x200.png" property="og:image:secure_url"/>
    <meta content="https://www.python.org/" property="og:url"/>
    <link href="/humans.txt" rel="author"/>
    <link href="https://peps.python.org/peps.rss" rel="alternate" title="Python Enhancement Proposals" type="application/rss+xml"/>
    <link href="https://www.python.org/jobs/feed/rss/" rel="alternate" title="Python Job Opportunities" type="application/rss+xml"/>
    <link href="https://pyfound.blogspot.com/feeds/posts/default?alt=rss" rel="alternate" title="Python Software Foundation News" type="application/rss+xml"/>
    <link href="https://blog.python.org/feeds/posts/default?alt=rss" rel="alternate" title="Python Insider" type="application/rss+xml"/>
    <link href="https://www.python.org/downloads/feed.rss" rel="alternate" title="Python Releases" type="application/rss+xml"/>
    <script type="application/ld+json">
     {
       "@context": "https://schema.org",
       "@type": "WebSite",
       "url": "https://www.python.org/",
       "potentialAction": {
         "@type": "SearchAction",
         "target": "https://www.python.org/search/?q={search_term_string}",
         "query-input": "required name=search_term_string"
       }
     }
    </script>
   </link>
  </link>
 </head>
 <body class="python home" id="homepage">
  <div id="touchnav-wrapper">
   <div class="do-not-print" id="nojs">
    <p>
     <strong>
      Notice:
     </strong>
     This page displays a fallback because interactive scripts did not run. Possible causes include disabled JavaScript or failure to load scripts or stylesheets.
    </p>
   </div>
   <!-- Sister Site Links -->
   <div class="top-bar do-not-print" id="top">
    <nav class="meta-navigation container">
     <div class="skip-link screen-reader-text">
      <a href="#content" title="Skip to content">
       Skip to content
      </a>
     </div>
     <a aria-hidden="true" class="jump-link" href="#python-network" id="close-python-network">
      <span aria-hidden="true" class="icon-arrow-down">
       <span>
        ▼
       </span>
      </span>
      Close
     </a>
     <ul class="menu" role="tree">
      <li class="python-meta current_item selectedcurrent_branch selected">
       <a class="current_item selectedcurrent_branch selected" href="/" title="The Python Programming Language">
        Python
       </a>
      </li>
      <li class="psf-meta">
       <a href="https://www.python.org/psf/" title="The Python Software Foundation">
        PSF
       </a>
      </li>
      <li class="docs-meta">
       <a href="https://docs.python.org" title="Python Documentation">
        Docs
       </a>
      </li>
      <li class="pypi-meta">
       <a href="https://pypi.org/" title="Python Package Index">
        PyPI
       </a>
      </li>
      <li class="jobs-meta">
       <a href="/jobs/" title="Python Job Board">
        Jobs
       </a>
      </li>
      <li class="shop-meta">
       <a href="/community/">
        Community
       </a>
      </li>
     </ul>
     <a aria-hidden="true" class="jump-link" href="#top" id="python-network">
      <span aria-hidden="true" class="icon-arrow-up">
       <span>
        ▲
       </span>
      </span>
      The Python Network
     </a>
    </nav>
   </div>
   <!-- Header elements -->
   <header class="main-header">
    <div class="container">
     <div class="site-headline">
      <a href="/">
       <img alt="python™" class="python-logo" src="/static/img/python-logo.png"/>
      </a>
     </div>
     <div class="options-bar-container do-not-print">
      <a class="donate-button" href="https://donate.python.org/">
       Donate
      </a>
      <div class="options-bar">
       <a class="jump-to-menu" href="#site-map" id="site-map-link">
        <span class="menu-icon">
         ≡
        </span>
        Menu
       </a>
       <form action="/search/" class="search-the-site" method="get">
        <fieldset title="Search Python.org">
         <span aria-hidden="true" class="icon-search">
         </span>
         <label class="screen-reader-text" for="id-search-field">
          Search This Site
         </label>
         <input class="search-field" id="id-search-field" name="q" placeholder="Search" tabindex="1" type="search" value=""/>
         <button class="search-button" id="submit" name="submit" tabindex="3" title="Submit this Search" type="submit">
          GO
         </button>
        </fieldset>
       </form>
       <span class="breaker">
       </span>
       <div aria-hidden="true" class="adjust-font-size">
        <ul aria-label="Adjust Text Size on Page" class="navigation menu">
         <li aria-haspopup="true" class="tier-1 last">
          <a class="action-trigger" href="#">
           <strong>
            <small>
             A
            </small>
            A
           </strong>
          </a>
          <ul class="subnav menu" role="menu">
           <li class="tier-2 element-1" role="menuitem">
            <a class="text-shrink" href="javascript:;" title="Make Text Smaller">
             Smaller
            </a>
           </li>
           <li class="tier-2 element-2" role="menuitem">
            <a class="text-grow" href="javascript:;" title="Make Text Larger">
             Larger
            </a>
           </li>
           <li class="tier-2 element-3" role="menuitem">
            <a class="text-reset" href="javascript:;" title="Reset any font size changes I have made">
             Reset
            </a>
           </li>
          </ul>
         </li>
        </ul>
       </div>
       <div class="winkwink-nudgenudge">
        <ul aria-label="Social Media Navigation" class="navigation menu">
         <li aria-haspopup="true" class="tier-1 last">
          <a class="action-trigger" href="#">
           Socialize
          </a>
          <ul class="subnav menu" role="menu">
           <li class="tier-2 element-1" role="menuitem">
            <a href="https://www.linkedin.com/company/python-software-foundation/">
             <i aria-hidden="true" class="fa fa-linkedin-square">
             </i>
             LinkedIn
            </a>
           </li>
           <li class="tier-2 element-2" role="menuitem">
            <a href="https://fosstodon.org/@ThePSF">
             <span aria-hidden="true" class="icon-mastodon">
             </span>
             Mastodon
            </a>
           </li>
           <li class="tier-2 element-3" role="menuitem">
            <a href="/community/irc/">
             <span aria-hidden="true" class="icon-freenode">
             </span>
             Chat on IRC
            </a>
           </li>
           <li class="tier-2 element-4" role="menuitem">
            <a href="https://twitter.com/ThePSF">
             <span aria-hidden="true" class="icon-twitter">
             </span>
             Twitter
            </a>
           </li>
          </ul>
         </li>
        </ul>
       </div>
       <span data-html-include="/authenticated">
       </span>
      </div>
      <!-- end options-bar -->
     </div>
     <nav class="python-navigation main-navigation do-not-print" id="mainnav">
      <ul aria-label="Main Navigation" class="navigation menu" role="menubar">
       <li aria-haspopup="true" class="tier-1 element-1" id="about">
        <a class="" href="/about/" title="">
         About
        </a>
        <ul aria-hidden="true" class="subnav menu" role="menu">
         <li class="tier-2 element-1" role="menuitem">
          <a href="/about/apps/" title="">
           Applications
          </a>
         </li>
         <li class="tier-2 element-2" role="menuitem">
          <a href="/about/quotes/" title="">
           Quotes
          </a>
         </li>
         <li class="tier-2 element-3" role="menuitem">
          <a href="/about/gettingstarted/" title="">
           Getting Started
          </a>
         </li>
         <li class="tier-2 element-4" role="menuitem">
          <a href="/about/help/" title="">
           Help
          </a>
         </li>
        </ul>
       </li>
       <li aria-haspopup="true" class="tier-1 element-2" id="downloads">
        <a class="" href="/downloads/" title="">
         Downloads
        </a>
        <ul aria-hidden="true" class="subnav menu" role="menu">
         <li class="tier-2 element-1" role="menuitem">
          <a href="/downloads/" title="">
           All releases
          </a>
         </li>
         <li class="tier-2 element-2" role="menuitem">
          <a href="/downloads/source/" title="">
           Source code
          </a>
         </li>
         <li class="tier-2 element-3" role="menuitem">
          <a href="/downloads/windows/" title="">
           Windows
          </a>
         </li>
         <li class="tier-2 element-4" role="menuitem">
          <a href="/downloads/macos/" title="">
           macOS
          </a>
         </li>
         <li class="tier-2 element-5" role="menuitem">
          <a href="/downloads/android/" title="">
           Android
          </a>
         </li>
         <li class="tier-2 element-6" role="menuitem">
          <a href="/downloads/ios/" title="">
           iOS
          </a>
         </li>
         <li class="tier-2 element-7" role="menuitem">
          <a href="/download/other/" title="">
           Other Platforms
          </a>
         </li>
         <li class="tier-2 element-8" role="menuitem">
          <a href="https://docs.python.org/3/license.html" title="">
           License
          </a>
         </li>
         <li class="tier-2 element-9" role="menuitem">
          <a href="/download/alternatives" title="">
           Alternative Implementations
          </a>
         </li>
        </ul>
       </li>
       <li aria-haspopup="true" class="tier-1 element-3" id="documentation">
        <a class="" href="/doc/" title="">
         Documentation
        </a>
        <ul aria-hidden="true" class="subnav menu" role="menu">
         <li class="tier-2 element-1" role="menuitem">
          <a href="/doc/" title="">
           Docs
          </a>
         </li>
         <li class="tier-2 element-2" role="menuitem">
          <a href="/doc/av" title="">
           Audio/Visual Talks
          </a>
         </li>
         <li class="tier-2 element-3" role="menuitem">
          <a href="https://wiki.python.org/moin/BeginnersGuide" title="">
           Beginner's Guide
          </a>
         </li>
         <li class="tier-2 element-4" role="menuitem">
          <a href="https://docs.python.org/3/faq/" title="">
           FAQ
          </a>
         </li>
         <li class="tier-2 element-5" role="menuitem">
          <a href="https://translations.python.org/" title="">
           Non-English Docs
          </a>
         </li>
         <li class="tier-2 element-6" role="menuitem">
          <a href="https://peps.python.org" title="">
           PEP Index
          </a>
         </li>
         <li class="tier-2 element-7" role="menuitem">
          <a href="https://wiki.python.org/moin/PythonBooks" title="">
           Python Books
          </a>
         </li>
         <li class="tier-2 element-8" role="menuitem">
          <a href="/doc/essays/" title="">
           Python Essays
          </a>
         </li>
        </ul>
       </li>
       <li aria-haspopup="true" class="tier-1 element-4" id="community">
        <a class="" href="/community/" title="">
         Community
        </a>
        <ul aria-hidden="true" class="subnav menu" role="menu">
         <li class="tier-2 element-1" role="menuitem">
          <a href="/community/diversity/" title="">
           Diversity
          </a>
         </li>
         <li class="tier-2 element-2" role="menuitem">
          <a href="/community/lists/" title="">
           Mailing Lists
          </a>
         </li>
         <li class="tier-2 element-3" role="menuitem">
          <a href="/community/irc/" title="">
           IRC
          </a>
         </li>
         <li class="tier-2 element-4" role="menuitem">
          <a href="/community/forums/" title="">
           Forums
          </a>
         </li>
         <li class="tier-2 element-5" role="menuitem">
          <a href="/psf/annual-report/2024/" title="">
           PSF Annual Impact Report
          </a>
         </li>
         <li class="tier-2 element-6" role="menuitem">
          <a href="/community/workshops/" title="">
           Python Conferences
          </a>
         </li>
         <li class="tier-2 element-7" role="menuitem">
          <a href="/community/sigs/" title="">
           Special Interest Groups
          </a>
         </li>
         <li class="tier-2 element-8" role="menuitem">
          <a href="/community/logos/" title="">
           Python Logo
          </a>
         </li>
         <li class="tier-2 element-9" role="menuitem">
          <a href="https://wiki.python.org/moin/" title="">
           Python Wiki
          </a>
         </li>
         <li class="tier-2 element-10" role="menuitem">
          <a href="/psf/conduct/" title="">
           Code of Conduct
          </a>
         </li>
         <li class="tier-2 element-11" role="menuitem">
          <a href="/community/awards" title="">
           Community Awards
          </a>
         </li>
         <li class="tier-2 element-12" role="menuitem">
          <a href="/psf/get-involved/" title="">
           Get Involved
          </a>
         </li>
         <li class="tier-2 element-13" role="menuitem">
          <a href="/psf/community-stories/" title="">
           Shared Stories
          </a>
         </li>
        </ul>
       </li>
       <li aria-haspopup="true" class="tier-1 element-5" id="success-stories">
        <a class="" href="/success-stories/" title="success-stories">
         Success Stories
        </a>
        <ul aria-hidden="true" class="subnav menu" role="menu">
         <li class="tier-2 element-1" role="menuitem">
          <a href="/success-stories/category/arts/" title="">
           Arts
          </a>
         </li>
         <li class="tier-2 element-2" role="menuitem">
          <a href="/success-stories/category/business/" title="">
           Business
          </a>
         </li>
         <li class="tier-2 element-3" role="menuitem">
          <a href="/success-stories/category/education/" title="">
           Education
          </a>
         </li>
         <li class="tier-2 element-4" role="menuitem">
          <a href="/success-stories/category/engineering/" title="">
           Engineering
          </a>
         </li>
         <li class="tier-2 element-5" role="menuitem">
          <a href="/success-stories/category/government/" title="">
           Government
          </a>
         </li>
         <li class="tier-2 element-6" role="menuitem">
          <a href="/success-stories/category/scientific/" title="">
           Scientific
          </a>
         </li>
         <li class="tier-2 element-7" role="menuitem">
          <a href="/success-stories/category/software-development/" title="">
           Software Development
          </a>
         </li>
        </ul>
       </li>
       <li aria-haspopup="true" class="tier-1 element-6" id="news">
        <a class="" href="/blogs/" title="News from around the Python world">
         News
        </a>
        <ul aria-hidden="true" class="subnav menu" role="menu">
         <li class="tier-2 element-1" role="menuitem">
          <a href="/blogs/" title="Python Insider Blog Posts">
           Python News
          </a>
         </li>
         <li class="tier-2 element-2" role="menuitem">
          <a href="/psf/newsletter/" title="Python Software Foundation Newsletter">
           PSF Newsletter
          </a>
         </li>
         <li class="tier-2 element-3" role="menuitem">
          <a href="https://pyfound.blogspot.com" title="PSF Blog">
           PSF News
          </a>
         </li>
         <li class="tier-2 element-4" role="menuitem">
          <a href="https://pycon.blogspot.com/" title="PyCon Blog">
           PyCon US News
          </a>
         </li>
         <li class="tier-2 element-5" role="menuitem">
          <a href="https://blog.python.org" title="News and updates from the Python core team">
           Python Insider
          </a>
         </li>
         <li class="tier-2 element-6" role="menuitem">
          <a href="https://planetpython.org/" title="Planet Python">
           News from the Community
          </a>
         </li>
        </ul>
       </li>
       <li aria-haspopup="true" class="tier-1 element-7" id="events">

In [9]:
names = soup.find_all("h2")

Python_names = []

for i in range(0, len(names)):
    Python_names.append(names[i].get_text(strip=True))

Python_names

['Get Started',
 'Download',
 'Docs',
 'Jobs',
 'Latest News',
 'Upcoming Events',
 'Success Stories',
 'Use Python for…',
 '>>>Python Software Foundation']

In [10]:
df = pd.DataFrame()

df['Python Website Sections'] = Python_names

df.to_csv('python.csv', index=True)

pd.read_csv("python.csv")

   Unnamed: 0        Python Website Sections
0           0                    Get Started
1           1                       Download
2           2                           Docs
3           3                           Jobs
4           4                    Latest News
5           5                Upcoming Events
6           6                Success Stories
7           7                Use Python for…
8           8  >>>Python Software Foundation

In [11]:
df

         Python Website Sections
0                    Get Started
1                       Download
2                           Docs
3                           Jobs
4                    Latest News
5                Upcoming Events
6                Success Stories
7                Use Python for…
8  >>>Python Software Foundation

In [12]:
pd.read_csv("python.csv")

   Unnamed: 0        Python Website Sections
0           0                    Get Started
1           1                       Download
2           2                           Docs
3           3                           Jobs
4           4                    Latest News
5           5                Upcoming Events
6           6                Success Stories
7           7                Use Python for…
8           8  >>>Python Software Foundation